# Configuration : Hôpital Moyen
# Auteurs: Abdelkarim & Marin

hospital:
  name: "Hôpital Régional"
  type: "medium"
  
resources:
  num_doctors: 6
  num_beds: 50
  
patient_flow:
  arrival_rate: 120  # patients par jour 
  
  priority_distribution:
    P1_RESUSCITATION: 0.05
    P2_EMERGENT: 0.15
    P3_URGENT: 0.30
    P4_LESS_URGENT: 0.35
    P5_NON_URGENT: 0.15

optimization:
  interval: 30
  time_limit: 20
  # Méthodes à tester: CP et MILP
  methods:
    CP:
      solver: "chuffed"
    MILP:
      solver: "PULP_CBC_CMD"

simulation:
  duration: 360  # minutes (6 heures)
  warmup: 30
  replications: 3

scenarios:
  baseline:
    name: "Journée Normale"
    arrival_multiplier: 1.0
  
  peak_flu:
    name: "Pic Grippal"
    arrival_multiplier: 1.3
